### ISSUE TITLE
Integration with prerender.io

### ISSUE THREAD

**Issue by junaid-malik-confiz** [Robert-W/react-prerender#3]
Hello, 

Our react-app is not rendering properly with prerender.io. Can this module help us in anyway to add value in the prerender.io.

Regards,
Junaid

**Comment by Robert-W** [comment]
@junaid-malik-confiz 
Sorry for the late response, I was not getting notifications for this repo. I'm not very familiar with Prerender.io but it seems like it will just render your page and cache the HTML content.

The purpose of this project was to actually pre-render content ahead of time and inject it into HTML, with a similar result to what they have but using a different method.  This project covered more of an edge case for apps my coworkers and I had worked on. We did not have access to the server, we were building client-side only apps and giving the source code to customers and they would host it on their servers. So we would run this after our build pipeline (webpack, grunt, or gulp) which resulted in our static html containing the pre-rendered content. It was also designed to be allowed to ignore modules that did not exist at compile time and were using AMD (Specifically the ESRI JavaScript API which is built on Dojo).

That being said, this module would be a replacement for Prerender.io in a sense that if you used it to pre-render your content, you no longer need their service to also prerender your content. 

There are many examples online of how to do server side rendering, including two of my other repo's with newer methods for pre-rendering, [esri-redux](https://github.com/Robert-W/esri-redux/blob/master/scripts/prerender.js), [mern-kit](https://github.com/Robert-W/mern-kit), and also facebook's own [Create-React-App](https://github.com/facebookincubator/create-react-app).

You may be able to lift the scripts I used in esri-redux and mern-kit to help with your own pre-render.
