### ISSUE TITLE
SyntaxError: Unexpected reserved word 'export'

### ISSUE THREAD

**Issue by paigefox** [Robert-W/react-prerender#4]
In the docs, it says `export class App extends React.Component` syntax is accepted, but every time I try to load the following:

```
var React = require('react');
var ReactDOM = require('react-dom');

export class App extends React.Component {
    constructor(props) {
        super(props);
      }

    render() {}
};

```

I get the error `SyntaxError: Unexpected reserved word`. Also, it appears to not know other JSX terms like `class`. 

current setup:
```

var target = path.join(__dirname, '/static/productlist.html');
    var component = path.join(__dirname, '/static/js/productlist');
    var mount = 'content';
var requirejs = {
  baseUrl: __dirname,
  paths: {
    'js': 'js',
    'vendor': 'vendor',
    'react': 'vendor/react/react.min',
  }
};

reactPrerender({
      target: target,
      component: component,
      mount: mount,
      requirejs: requirejs,
      exportName: "App",
    })

```

**Comment by Robert-W** [comment]
Hi @paigefox,

This module is actually meant as a post-build module and does not build es6 code for you. It was designed to work specifically with AMD modules and code bases that used modules that would not exist at build time, but only at run time.

The use case for this is for when you build a react application and compile it with webpack, babel, or some other tool to the AMD format (Dojo and RequireJS use this module format).  This module would attempt to load your component in node, render it to a string, and inject it into your static html page.

It sounds like you are pointing this to an ES6 component.  If you can share some details about your deployment process I might be able to help you get this working or point you to another module better suited for your needs.  There are some other tools to allow you to require raw ES6 components in node and render them to strings with react-dom/server, or build them to commonJS first and then render them to a string so they can be injected into your html.
